Actividad1_FruitStore/Models/Productos.cs
using System;
using System.Collections.Generic;

namespace Actividad1_FruitStore.Models
{
    public partial class Productos
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int? IdCategoria { get; set; }
        public decimal? Precio { get; set; }
        public string UnidadMedida { get; set; }
        public string Descripcion { get; set; }

        public virtual Categorias IdCategoriaNavigation { get; set; }
    }
}

Actividad1_FruitStore/Models/ViewModels/ProductosViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Actividad1_FruitStore.Models.ViewModels
{
    public class ProductosViewModel
    {
        public IEnumerable<Categorias> Categorias { get; set; }
        public Productos Producto { get; set; }
        public IFormFile Archivo { get; set; }
        public string Imagen { get; set; }
    }
}

Actividad1_FruitStore/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Actividad1_FruitStore.Models;
using Actividad1_FruitStore.Models.ViewModels;
using Actividad1_FruitStore.Repositories;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

namespace Actividad1_FruitStore.Controllers
{
    public class ProductosController : Controller
    {
        public IWebHostEnvironment Enviroment { get; set; }
        public ProductosController(IWebHostEnvironment env)
        {
            Enviroment = env;
        }

        public IActionResult Index()
        {
            ProductosIndexViewModel vm = new ProductosIndexViewModel();
            fruteriashopContext context = new fruteriashopContext();
            CategoriasRepository categoriarepos = new CategoriasRepository(context);
            ProductosRepository productosrepos = new ProductosRepository(context);


            int? id = null;

            // AGREGUÉ EL WHERE PARA QUE NO SE MUESTRE LA CATEGORÍA SI FUÉ ELIMINADA DE MANERA LOGICA
            vm.Categorias = categoriarepos.GetAll().Where(x => x.Eliminado == false).OrderBy(x => x.Nombre);
            vm.Productos = productosrepos.GetProductosByCategoria(id);


            return View(vm);
        }

        [HttpPost]
        public IActionResult Index(ProductosIndexViewModel vm)
        {
            fruteriashopContext context = new fruteriashopContext();
            CategoriasRepository categoriarepos = new CategoriasRepository(context);
            ProductosRepository productosrepos = new ProductosRepository(context);

            // AGREGUÉ EL WHERE PARA QUE NO SE MUESTRE LA CATEGORÍA SI FUÉ ELIMINADA DE MANERA LOGICA
            vm.Categorias = categoriarepos.GetAll().Where(x => x.Eliminado == false).OrderBy(x => x.Nombre);

            if (vm.IdCategoria == 0)
            {
                int? id = null;
                vm.Productos = productosrepos.GetProductosByCategoria(id);
            }
            else
            {
                vm.Productos = productosrepos.GetProductosByCategoria(vm.IdCategoria);
            }

            return View(vm);
        }

        public IActionResult Agregar()
        {
            ProductosViewModel vm = new ProductosViewModel();
            fruteriashopContext context = new fruteriashopContext();
            CategoriasRepository repos = new CategoriasRepository(context);
            vm.Categorias = repos.GetAll().Where(x => x.Eliminado == false).OrderBy(x => x.Nombre);
            return View(vm);
        }
        [HttpPost]
        public IActionResult Agregar(ProductosViewModel vm)
        {
            fruteriashopContext context = new fruteriashopContext();
            try
            {
                if (vm.Archivo == null)
                {
                    ModelState.AddModelError("", "Debe seleccionar la imagen del producto.");
                    CategoriasRepository categoriasrepos = new CategoriasRepository(context);
                    vm.Categorias = categoriasrepos.GetAll().Where(x => x.Eliminado == false).OrderBy(x => x.Nombre);
                    return View(vm);
                }
                else
                {
                    if (vm.Archivo.ContentType != "image/jpeg" || vm.Archivo.Length > 1024 * 1024 * 2)
                    {
                        ModelState.AddModelError("", "Debe seleccionar un archivo jpg de menos de 2MB.");
                        CategoriasRepository repos = new CategoriasRepository(context);
                        vm.Categorias = repos.GetAll().Where(x => x.Eliminado == false).OrderBy(x => x.Nombre);
                        return View(vm);
                    }
                }


                ProductosRepository productosrepos = new ProductosRepository(context);
                productosrepos.Insert(vm.Producto);

                if (vm.Archivo != null)
                {
                    FileStream fs = new FileStream(Enviroment.WebRootPath + "/img_frutas/" + vm.Producto.Id + ".jpg", FileMode.Create);
                    vm.Archivo.CopyTo(fs);
                    fs.Close();
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                CategoriasRepository repos = new CategoriasRepository(context);
                vm.Categorias = repos.GetAll().OrderBy(x => x.Nombre);
                return View(vm);
            }
        }

        public IActionResult Editar(int Id)
        {
            fruteriashopContext context = new fruteriashopContext();
            ProductosRepository repos = new ProductosRepository(context);
            ProductosViewModel vm = new ProductosViewModel();
            vm.Producto = repos.Get(Id);

            if (vm.Producto == null)
            {
                return RedirectToAction("Index");
            }

            CategoriasRepository cr = new CategoriasRepository(context);
            vm.Categorias = cr.GetAll().Where(x => x.Eliminado == false).OrderBy(x => x.Nombre);

            if (System.IO.File.Exists(Enviroment.WebRootPath + $"/img_frutas/{vm.Producto.Id}.jpg"))
            {
                vm.Imagen = vm.Producto.Id + ".jpg";
            }
            else
            {
                vm.Imagen = "no-disponible.png";
            }

            return View(vm);
        }
        [HttpPost]
        public IActionResult Editar(ProductosViewModel vm)
        {
            fruteriashopContext context = new fruteriashopContext();

            if (vm.Archivo != null)
            {
                if (vm.Archivo.ContentType != "image/jpeg" || vm.Archivo.Length > 1024 * 1024 * 2)
                {
                    ModelState.AddModelError("", "Debe seleccionar un archivo jpg de menos de 2MB.");
                    CategoriasRepository repos = new CategoriasRepository(context);
                    vm.Categorias = repos.GetAll().Where(x => x.Eliminado == false).OrderBy(x => x.Nombre);
                    return View(vm);
                }
            }

            try
            {
                ProductosRepository repos = new ProductosRepository(context);

                var producto = repos.Get(vm.Producto.Id);

                if (producto != null)
                {
                    producto.Nombre = vm.Producto.Nombre;
                    producto.Precio = vm.Producto.Precio;
                    producto.IdCategoria = vm.Producto.IdCategoria;
                    producto.Descripcion = vm.Producto.Descripcion;
                    producto.UnidadMedida = vm.Producto.UnidadMedida;
                    repos.Update(producto);

                    if (vm.Archivo != null)
                    {
                        FileStream fs = new FileStream(Enviroment.WebRootPath + "/img_frutas/" + vm.Producto.Id + ".jpg", FileMode.Create);
                        vm.Archivo.CopyTo(fs);
                        fs.Close();
                    }
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                CategoriasRepository repos = new CategoriasRepository(context);
                vm.Categorias = repos.GetAll().OrderBy(x => x.Nombre);
                return View(vm);
            }
        }

        public IActionResult Eliminar(int Id)
        {
            using (fruteriashopContext context = new fruteriashopContext())
            {
                ProductosRepository repos = new ProductosRepository(context);
                var p = repos.Get(Id);

                if (p != null)
                {
                    return View(p);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
        }
        [HttpPost]
        public IActionResult Eliminar(Productos p)
        {
            using (fruteriashopContext context = new fruteriashopContext())
            {
                ProductosRepository repos = new ProductosRepository(context);
                var producto = repos.Get(p.Id);

                if (producto != null)
                {
                    repos.Delete(producto);
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "El producto no existe o ya fué eliminado");
                    return View();
                }
            }
        }
    }
}

Actividad1_FruitStore/Views/Productos/Agregar.cshtml
@model Actividad1_FruitStore.Models.ViewModels.ProductosViewModel

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "_LayoutAdmin";
}

<form method="post" asp-action="Agregar" asp-controller="Productos" enctype="multipart/form-data">
    <div>
        <h1>Agregar Producto</h1>

        <label>Nombre:</label>
        <input type="text" asp-for="Producto.Nombre" required="required" />

        <label>Categoría:</label>
        <select asp-for="Producto.IdCategoria" asp-items="@(new SelectList(Model.Categorias,"Id","Nombre"))" id="cmbCategoria" required="required">
            <option selected="selected" value="">-- Seleccionar categoria --</option>
        </select>

        <label>Unidad de Medida:</label>
        <input type="text" asp-for="Producto.UnidadMedida" required="required" />

        <label>Precio:</label>
        <input type="number" asp-for="Producto.Precio" required="required" step="0.01" min="0.1" />

        <label>Descripción</label>
        <textarea rows="2" cols="20" asp-for="Producto.Descripcion" required="required">
</textarea>

        <label>Imagen:</label>
        <input type="file" id="fileUpload1" accept="image/jpg" asp-for="Archivo" onchange="mostrarImagen(this)"/>

        <img id="imagePreview" src="~/img_frutas/no-disponible.png" alt="Vista previa de la imagen" />

        <div class="botones">
            <p id="error">
                @Html.ValidationSummary()
            </p>
            <input type="submit" value="Agregar" id="btnAgregar" />
            <a asp-controller="Productos" asp-action="Index">
                <input type="button" value="Cancelar" id="btnCancelar" formnovalidate="formnovalidate" />
            </a>
            
        </div>
    </div>
</form>
<script>
    function mostrarImagen(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                document.getElementById("imagePreview").src=e.target.result;
            }
            reader.readAsDataURL(input.files[0]);
        }
    }

</script>

Actividad1_FruitStore/Views/Productos/Editar.cshtml
@model Actividad1_FruitStore.Models.ViewModels.ProductosViewModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = "_LayoutAdmin";
}

<form method="post" asp-controller="Productos" asp-action="Editar" enctype="multipart/form-data">
    <div>
        <h1>Editar Producto</h1>

        <input type="hidden" id="idProducto" asp-for="Producto.Id"/>

        <label>Nombre:</label>
        <input type="text" id="txtNombre" required="required" asp-for="Producto.Nombre"/>

        <label>Categoría:</label>
        <select id="cmbCategoria" required="required" asp-for="Producto.IdCategoria" asp-items="@(new SelectList(Model.Categorias,"Id","Nombre"))">
            <option selected="selected" value="">-- Seleccionar categoria --</option>
        </select>

        <label>Unidad de Medida:</label>
        <input type="text" id="txtUnidadMedida" required="required" asp-for="Producto.UnidadMedida"/>

        <label>Precio:</label>
        <input type="number" id="txtPrecio" required="required" step="0.01" min="0.1" asp-for="Producto.Precio" />

        <label>Descripción</label>
        <textarea rows="2" cols="20" id="txtDescripcion" required="required" asp-for="Producto.Descripcion">
</textarea>

        <label>Imagen:</label>
        <input type="file" id="fileUpload1" accept="image/jpg" onchange="mostrarImagen(this)" asp-for="Archivo"/>

        <img id="imagePreview" src="~/img_frutas/@Model.Imagen" alt="Vista previa de la imagen" />

        <div class="botones">
            <p id="error">
                @Html.ValidationSummary()
            </p>
            <input type="submit" value="Guardar" id="btnGuardar" />
            <a asp-controller="Productos" asp-action="Index">
                <input type="button" value="Cancelar" id="btnCancelar" formnovalidate="formnovalidate" />
            </a>
        </div>
    </div>
</form>
<script>
    function mostrarImagen(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                document.querySelector('#imagePreview').src= e.target.result;
            }
            reader.readAsDataURL(input.files[0]);
        }
    }

</script>

Actividad1_FruitStore/Views/Productos/Eliminar.cshtml
@model Actividad1_FruitStore.Models.Productos
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "_LayoutAdmin";
}

<form method="post" asp-action="Eliminar" asp-controller="Productos">
    <div>
        <h1>Eliminar Producto</h1>

        <input type="hidden" id="id" asp-for="Id"/>

        <p>¿Está seguro de eliminar el producto  "<span id="nombreCategoria">@Model.Nombre</span>"?</p>

        <div class="botones">
            <p id="error"></p>
            <input type="submit" value="Si" id="btnSi" />
            <a asp-action="Index" asp-controller="Productos">
                <input type="button" value="No" id="btnNo" formnovalidate="formnovalidate" />
            </a>
        </div>
    </div>
</form>

Actividad1_FruitStore/Views/Productos/Index.cshtml
@model Actividad1_FruitStore.Models.ViewModels.ProductosIndexViewModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = "_LayoutAdmin";
}

<h1>Administrar Productos</h1>


<section class="listado">
    <form method="post" action="~/Productos/Index">
        @*<select name="IdCategoria" id="ddlCategorias" style="width:100%;margin: 10px 0" onchange="this.form.submit()">
                <option value="">Ver todos los productos</option>
                @foreach (var item in Model.Categorias)
                {
                    if (item.Id == Model.IdCategoria)
                    {
                        <option selected value="@item.Id">@item.Nombre</option>
                    }
                    else
                    {
                        <option value="@item.Id">@item.Nombre</option>
                    }
                }
            </select>*@


        <select name="IdCategoria" id="ddlCategorias" asp-for="IdCategoria" asp-items="@(new SelectList(Model.Categorias,"Id","Nombre"))" style="width:100%;margin: 10px 0" onchange="this.form.submit()">
            <option value="">Ver todos los productos</option>
        </select>
    </form>

    <a id="lnkNueva" class="mark" href="~/Productos/Agregar">
        <h1>Nuevo Producto...</h1>
        <h2></h2>
        <h2></h2>
        <h2></h2>
        <div class="image">
            <img src="../images/addb.png" />
        </div>
        <h2></h2>
        <h2></h2>
        <div class="botones">
            <img src="../images/add.png" />
        </div>
    </a>

    @foreach (var item in Model.Productos)
    {
        <div class="card">
            <h1>@item.Nombre</h1>
            <h2>Tipo: @item.IdCategoriaNavigation.Nombre</h2>
            <h2>Unidad de Medida: @item.UnidadMedida</h2>
            <h2>Precio: @item.Precio.Value.ToString("$ 0.00")</h2>
            <h2 title="@item.Descripcion">Descripción: @(item.Descripcion.Length>50?item.Descripcion.Substring(0,50)+"...":item.Descripcion)</h2>
            <div class="image">
                <img src="~/img_frutas/@(item.Id).jpg?v=1" />
            </div>
            <div class="botones">
                <a href="~/Productos/Editar/@item.Id" class="btnEditar"></a>
                <a href="~/Productos/Eliminar/@item.Id" class="btnBorrar"></a>
            </div>
        </div>
    }


</section>